language: java
jdk:
  - openjdk11

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

services:
  - mysql

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - qkrdbsk28@naver.com