language: java
jdk:
  - openjdk11

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

services:
  - mysql

env:
  - MYSQL_HOST=$MYSQL_HOST
  - MYSQL_PORT=$MYSQL_PORT
  - MYSQL_USER=$MYSQL_USER
  - MYSQL_PASSWORD=$MYSQL_PASSWORD

script: "./gradlew clean build"

before_deploy:
  - zip -r everyday_coding
  - mkdir -p deploy
  - mv everyday_coding.zip deploy/everyday_coding.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: everyday-coding-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - qkrdbsk28@naver.com